export const Theme_Colors = {
  back_ground_dark: "#05050C",
  back_ground_light: "#FAFAFA",
};

export const App_Colors = {
  White: "#ffffff",
  Black: "#000000",
  Text_White: "#FAFAFA",
  Text_Black: "#0E0E0E",
  Text_Black_1: "#0F0F0F",
  Primary_Color_Bg: "#f3ebff",
  Primary_Color_Bg_Hover: "#e3d0ff",
  Primary_Color_Border: "#cdabff",
  Primary_Color_Border_Hover: "#b584ff",
  Primary_Color_Hover: "#9f5eff",
  Primary_Color_Base: "#8a3bff",
  Primary_Color_Active: "#7532d9",
  Primary_Color_Text: "#4f2291",
  Primary_Color_Text_Hover: "#622ab5",
  Primary_Color_Text_Active: "#3e1b73",
  Neutral_Color: "#787878",
  Neutral_Color_2: "#DFDFDF",
  Neutral_Color_3: "#C5C5C5",
  Neutral_Color_4: "#AAAAAA",
  Neutral_Color_5: "#909090",
  Neutral_Color_6: "#787878",
  Neutral_Color_8: "#555555",
  Pastel_Pink_Color: "#FFEDF6",
  Pastel_Green_Color: "#EFFFF6",
  Pastel_Lavender_Color: "#F4ECFF",
  Pastel_Blue_Color: "#E9E9FF",
  Pastel_Yellow_Color: "#FDF7E9",
  Image_BG_Color: "#AC9BC5",
};
